apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: thanos
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minio-data"